import os
from flask import Flask
from flask_migrate import Migrate, init, upgrade
from context.database import db
import secrets
from dotenv import load_dotenv
from routes.blueprint import bp
from context.constants import STATIC_FOLDER
from alembic.command import revision
from alembic.config import Config

def create_app():
    load_dotenv()
    app = Flask(__name__, template_folder='../templates')
    
    app.register_blueprint(bp)
    app.config['SECRET_KEY'] = secrets.token_hex(nbytes=8)
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ['DATABASE_URL'] 
    app.config['STATIC_FOLDER'] = STATIC_FOLDER

    db.init_app(app)
    with app.app_context():
        setup_migrations(app, db)

    return app

def setup_migrations(app, db):
    db.session.close_all()

    # setup migrations
    Migrate(app, db)

    # check if migrations folder does not exists, then initialize
    if not os.path.exists('migrations'):
        # Create a migrations folder and the initial migration
        with app.app_context():
            init()
            upgrade()

    # Autogenerate migrations and apply them
    with app.app_context():
        alembic_cfg = Config(os.path.join(os.getcwd(), 'migrations', 'alembic.ini'))
        alembic_cfg.set_main_option('script_location', os.path.join(os.getcwd(), 'migrations'))
        revision(alembic_cfg, autogenerate=True, message="autogenerated migration")
        upgrade()