"""Added conversation column to VoterCall model

Revision ID: 112afb96fc64
Revises: 
Create Date: 2023-05-13 03:58:38.315206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112afb96fc64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter_call', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter_call', schema=None) as batch_op:
        batch_op.drop_column('conversation')

    # ### end Alembic commands ###
