"""autogenerated migration

Revision ID: 1ed5594c8fa4
Revises: 4444e9b4a984
Create Date: 2023-06-21 16:25:04.390605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed5594c8fa4'
down_revision = '4444e9b4a984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
