"""empty message

Revision ID: 251b01a31627
Revises: b77fd77324ac
Create Date: 2023-07-09 19:12:04.377802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251b01a31627'
down_revision = 'b77fd77324ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('campaign_goal', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('campaign_fallback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('example_interactions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('campaign_manager_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('communications_director_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('field_director_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('interactions_sent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interactions_delivered', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interactions_responded', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interactions_converted', sa.Integer(), nullable=True))
        batch_op.drop_column('campaign_information')

    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_achieved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rating_explanation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('campaign_relevance_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('campaign_relevance_explanation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('campaign_relevance_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('insights_about_issues', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('insights_about_recipient', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.drop_column('insights_about_recipient')
        batch_op.drop_column('insights_about_issues')
        batch_op.drop_column('campaign_relevance_summary')
        batch_op.drop_column('campaign_relevance_explanation')
        batch_op.drop_column('campaign_relevance_score')
        batch_op.drop_column('rating')
        batch_op.drop_column('rating_explanation')
        batch_op.drop_column('goal_achieved')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_information', sa.TEXT(), nullable=True))
        batch_op.drop_column('interactions_converted')
        batch_op.drop_column('interactions_responded')
        batch_op.drop_column('interactions_delivered')
        batch_op.drop_column('interactions_sent')
        batch_op.drop_column('field_director_summary')
        batch_op.drop_column('communications_director_summary')
        batch_op.drop_column('campaign_manager_summary')
        batch_op.drop_column('example_interactions')
        batch_op.drop_column('campaign_fallback')
        batch_op.drop_column('campaign_goal')
        batch_op.drop_column('campaign_prompt')

    # ### end Alembic commands ###
