"""Added key examples to campaign object so we don't look it up every message

Revision ID: 2a51aec5c3fa
Revises: b1913e5fd586
Create Date: 2024-09-29 00:43:39.282291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a51aec5c3fa'
down_revision = 'b1913e5fd586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_key_examples', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('campaign_key_examples')

    # ### end Alembic commands ###
