"""autogenerated migration

Revision ID: 4444e9b4a984
Revises: 6b0416b5567c
Create Date: 2023-06-21 12:31:29.171606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4444e9b4a984'
down_revision = '6b0416b5567c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
