"""empty message

Revision ID: 68f539ece131
Revises: cbca9c53e2f0
Create Date: 2023-12-30 11:13:01.979384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f539ece131'
down_revision = 'cbca9c53e2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter_profile', schema=None) as batch_op:
        batch_op.alter_column('preferred_contact_method',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter_profile', schema=None) as batch_op:
        batch_op.alter_column('preferred_contact_method',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
