"""autogenerated migration

Revision ID: 6b0416b5567c
Revises: 
Create Date: 2023-06-21 12:31:23.443246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0416b5567c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=50), nullable=True),
    sa.Column('campaign_information', sa.Text(), nullable=True),
    sa.Column('campaign_end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(length=50), nullable=True),
    sa.Column('recipient_information', sa.Text(), nullable=True),
    sa.Column('recipient_phone_number', sa.String(length=100), nullable=True),
    sa.Column('recipient_profile', sa.JSON(), nullable=True),
    sa.Column('recipient_engagement_history', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(length=50), nullable=True),
    sa.Column('sender_information', sa.Text(), nullable=True),
    sa.Column('sender_schedule', sa.JSON(), nullable=True),
    sa.Column('sender_phone_number', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twilio_conversation_sid', sa.String(length=50), nullable=True),
    sa.Column('conversation', sa.JSON(), nullable=True),
    sa.Column('interaction_type', sa.String(length=50), nullable=True),
    sa.Column('interaction_goal', sa.Text(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('recipient_outreach_schedule', sa.JSON(), nullable=True),
    sa.Column('interaction_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipient.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['sender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interaction')
    op.drop_table('sender')
    op.drop_table('recipient')
    op.drop_table('campaign')
    # ### end Alembic commands ###
