"""autogenerated migration

Revision ID: 9d9a6d116371
Revises: 1ed5594c8fa4
Create Date: 2023-06-21 16:25:10.121906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9a6d116371'
down_revision = '1ed5594c8fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
