"""Removed field from campaign to avoid duplication

Revision ID: abf7031a7411
Revises: ef63dfa58e4d
Create Date: 2023-09-03 20:28:58.270932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf7031a7411'
down_revision = 'ef63dfa58e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('campaign_fallback')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_fallback', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
