"""Added opted_out column to sender_voter_relationships table

Revision ID: b1913e5fd586
Revises: 8649297293dd
Create Date: 2024-09-28 12:17:28.161051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1913e5fd586'
down_revision = '8649297293dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sender_voter_relationship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opted_out', sa.Boolean(), nullable=True))

    with op.batch_alter_table('voter_profile', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['voter_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter_profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('sender_voter_relationship', schema=None) as batch_op:
        batch_op.drop_column('opted_out')

    # ### end Alembic commands ###
