"""empty message

Revision ID: b25fba0c347d
Revises: cfd2ec073dad
Create Date: 2023-09-29 23:52:37.416235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25fba0c347d'
down_revision = 'cfd2ec073dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'agent', ['agent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('agent_id')

    # ### end Alembic commands ###
