"""empty message

Revision ID: c4caab3fd940
Revises: 
Create Date: 2023-08-04 10:12:49.789464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4caab3fd940'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(length=50), nullable=True),
    sa.Column('sender_information', sa.Text(), nullable=True),
    sa.Column('sender_schedule', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_name', sa.String(length=50), nullable=True),
    sa.Column('voter_phone_number', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audience_name', sa.String(length=50), nullable=True),
    sa.Column('audience_information', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['sender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=50), nullable=True),
    sa.Column('campaign_prompt', sa.Text(), nullable=True),
    sa.Column('campaign_goal', sa.Text(), nullable=True),
    sa.Column('campaign_fallback', sa.Text(), nullable=True),
    sa.Column('example_interactions', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('campaign_end_date', sa.Date(), nullable=True),
    sa.Column('campaign_manager_summary', sa.Text(), nullable=True),
    sa.Column('communications_director_summary', sa.Text(), nullable=True),
    sa.Column('field_director_summary', sa.Text(), nullable=True),
    sa.Column('interactions_sent', sa.Integer(), nullable=True),
    sa.Column('interactions_delivered', sa.Integer(), nullable=True),
    sa.Column('interactions_responded', sa.Integer(), nullable=True),
    sa.Column('interactions_converted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['sender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('phone_number_after_code', sa.String(length=20), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['sender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sender_voter_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('funnel_stage', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['sender.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voter_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('policy_preferences', sa.Text(), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['voter_id'], ['voter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audience_voter',
    sa.Column('audience_id', sa.Integer(), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audience_id'], ['audience.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voter.id'], )
    )
    op.create_table('campaign_audience',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('audience_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audience_id'], ['audience.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'audience_id')
    )
    op.create_table('interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twilio_conversation_sid', sa.String(length=50), nullable=True),
    sa.Column('conversation', sa.JSON(), nullable=True),
    sa.Column('interaction_type', sa.String(length=50), nullable=True),
    sa.Column('interaction_goal', sa.Text(), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('voter_outreach_schedule', sa.JSON(), nullable=True),
    sa.Column('interaction_status', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('goal_achieved', sa.Boolean(), nullable=True),
    sa.Column('rating_explanation', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('campaign_relevance_score', sa.Integer(), nullable=True),
    sa.Column('campaign_relevance_explanation', sa.Text(), nullable=True),
    sa.Column('campaign_relevance_summary', sa.Text(), nullable=True),
    sa.Column('insights_about_issues', sa.JSON(), nullable=True),
    sa.Column('insights_about_voter', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['sender.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interaction')
    op.drop_table('campaign_audience')
    op.drop_table('audience_voter')
    op.drop_table('voter_profile')
    op.drop_table('sender_voter_relationship')
    op.drop_table('phone_number')
    op.drop_table('campaign')
    op.drop_table('audience')
    op.drop_table('voter')
    op.drop_table('sender')
    # ### end Alembic commands ###
