"""empty message

Revision ID: c5c7217f8614
Revises: 112afb96fc64
Create Date: 2023-05-14 01:35:42.096675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c5c7217f8614'
down_revision = '112afb96fc64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voter_call')
    with op.batch_alter_table('voter_communication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twilio_conversation_sid', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('communication_type', sa.String(length=50), nullable=True))
        batch_op.drop_column('twilio_call_sid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter_communication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twilio_call_sid', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('communication_type')
        batch_op.drop_column('twilio_conversation_sid')

    op.create_table('voter_call',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('twilio_call_sid', sa.VARCHAR(length=50), nullable=True),
    sa.Column('voter_id', sa.INTEGER(), nullable=True),
    sa.Column('candidate_id', sa.INTEGER(), nullable=True),
    sa.Column('race_id', sa.INTEGER(), nullable=True),
    sa.Column('conversation', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
