"""empty message

Revision ID: cbca9c53e2f0
Revises: 454d0b676b7e
Create Date: 2023-12-30 11:01:17.362612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbca9c53e2f0'
down_revision = '454d0b676b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_interaction', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter_profile', schema=None) as batch_op:
        batch_op.drop_column('last_interaction')
        batch_op.drop_column('background')

    # ### end Alembic commands ###
