"""empty message

Revision ID: cfd2ec073dad
Revises: a66dbcef884a
Create Date: 2023-09-29 17:19:40.576980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd2ec073dad'
down_revision = 'a66dbcef884a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_history', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('available_actions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_column('available_actions')
        batch_op.drop_column('conversation_history')

    # ### end Alembic commands ###
