"""Add new field to sender

Revision ID: ef63dfa58e4d
Revises: fae6563d0018
Create Date: 2023-09-03 20:17:39.677230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef63dfa58e4d'
down_revision = 'fae6563d0018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audience', schema=None) as batch_op:
        batch_op.alter_column('audience_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('example_interactions')

    with op.batch_alter_table('sender', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fallback_url', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('example_interactions', sa.Text(), nullable=True))
        batch_op.alter_column('sender_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sender', schema=None) as batch_op:
        batch_op.alter_column('sender_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('example_interactions')
        batch_op.drop_column('fallback_url')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example_interactions', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('audience', schema=None) as batch_op:
        batch_op.alter_column('audience_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
