"""empty message

Revision ID: f58af8956a45
Revises: 1ea00b755ea8
Create Date: 2023-12-18 14:23:32.105262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58af8956a45'
down_revision = '1ea00b755ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sender', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_email', sa.String(length=100), nullable=True))

    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voter_email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.drop_column('voter_email')

    with op.batch_alter_table('sender', schema=None) as batch_op:
        batch_op.drop_column('sender_email')

    # ### end Alembic commands ###
