"""empty message

Revision ID: ffd267ccf7eb
Revises: b25fba0c347d
Create Date: 2023-10-03 17:07:51.098164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd267ccf7eb'
down_revision = 'b25fba0c347d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sender', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sender', schema=None) as batch_op:
        batch_op.drop_column('alert_phone_number')

    # ### end Alembic commands ###
